name: django
channels:
  - phygbu
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - django
  - mamba
  - ipython
  - django-mathfilters
  - django-import-export
  - django-suit
  - django-tinymce
  - tablib
  - djangorestframework
  - django-ajax-selects
  - django-constance
  - django-grappelli
  - django-photologue
  - django-simple-file-handler
  - psycopg2
  - django-sitetree
  - django-bootstrap5
  - django-extra-views
  - simple_html_table
  - django-picklefield
  - django-ical
  - django-autocomplete-light
  - django-bootstrap-datepicker-plus=5.0.5
  - django-floppyforms
  - ca-certificates
  - certifi
  - openssl
  - gunicorn
  - multiprocess
  - black
  - isort
  - codespell
  - django-htmx
  - celery
  - django-extensions
  - django-mptt
  - djhtml
  - whitenoise=6.6.0
  - django-auth-adfs
  - pyjwt
  - anaconda-client
  - nh3
  - django-easy-pdf3
  - pygraphviz
prefix: /usr/lib/miniconda3/envs/django
