name: django
channels:
  - phygbu
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - django=5.2.11
  - mamba
  - ipython
  - django-mathfilters
  - django-import-export=4.3.7
  - django-suit=2.0beta4
  - django-tinymce
  - tablib
  - djangorestframework
  - django-ajax-selects
  - django-constance=4.3.2
  - django-grappelli
  - django-photologue
  - django-simple-file-handler
  - psycopg2
  - django-sitetree
  - django-bootstrap5
  - django-extra-views
  - simple_html_table
  - django-picklefield
  - django-ical
  - django-autocomplete-light
  - django-bootstrap-datepicker-plus=5.0.5
  - django-floppyforms
  - ca-certificates
  - certifi
  - openssl
  - gunicorn
  - multiprocess
  - black
  - isort
  - codespell
  - django-htmx
  - celery=5.5.2
  - django-extensions
  - djhtml
  - whitenoise=6.6.0
  - django-auth-adfs
  - pyjwt
  - anaconda-client
  - nh3
  - django-easy-pdf3
  - pygraphviz
  - django-cors-headers
  - django-upgrade=1.25
  - azure-storage-blob
  - beautifulsoup4
  - celery-batches
  - chardet
  - dal-admin-filters
  - dateparser
  - dj-easy-pdf
  - django-admin-multi-select-filter
  - django-admin-sortable
  - django-admin-sortable2
  - django-appconf
  - django-baton
  - django-bootstrap3
  - django-bootstrap4
  - django-braces
  - django-celery-beat
  - django-celery-results
  - django-classy-tags
  - django-codemirror2
  - django-colorful
  - django-common-helpers
  - django-constrainedfilefield
  - django-cookie-law
  - django-cron
  - django-datetime-widget2
  - django-email-obfuscator
  - django-fieldsets-with-inlines
  - django-filebrowser
  - django-filebrowser-no-grappelli
  - django-filter
  - django-formtools
  - django-mathjax
  - django-microsoft-auth
  - django-multi-form-view
  - django-multiupload
  - django-oauth-toolkit
  - django-smart-selects
  - django-sortedm2m
  - django-stubs
  - django-stubs-ext
  - django-tables2
  - django-tags-input
  - django_auth_ldap_ad
  - djlint
  - exifread
  - html-for-docx
  - html2docx
  - json-datetime
  - matplotlib
  - netaddr
  - numpy
  - oauth2
  - openpyxl
  - pandas
  - pillow
  - pypdf
  - pyquery
  - python-magic
  - pytz
  - scikit-image
  - scipy
  - spyder
  - spyder-kernels
  - typing
  - urllib3
  - weasyprint
  - xlsx2html
  - xlsxwriter
  - django-mptt
prefix: /usr/lib/miniconda3/envs/django
